// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiUU2azAcgwCZpnHKeRbyHGCAB5yeryoU',
    appId: '1:493354046889:web:60e67b1b787d2d1274a0b8',
    messagingSenderId: '493354046889',
    projectId: 'atma-palm-app-e2eb1',
    authDomain: 'atma-palm-app-e2eb1.firebaseapp.com',
    storageBucket: 'atma-palm-app-e2eb1.firebasestorage.app',
    measurementId: 'G-L0W9MY183P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28yd43S1v9cWtpAVf22Qkct3z2zphwZw',
    appId: '1:493354046889:android:8d77c628b69ce23f74a0b8',
    messagingSenderId: '493354046889',
    projectId: 'atma-palm-app-e2eb1',
    storageBucket: 'atma-palm-app-e2eb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBs1DVAp4D-uxsJIf6BPvEHvhgCGPvizI',
    appId: '1:493354046889:ios:274e3a24706decff74a0b8',
    messagingSenderId: '493354046889',
    projectId: 'atma-palm-app-e2eb1',
    storageBucket: 'atma-palm-app-e2eb1.firebasestorage.app',
    iosBundleId: 'com.example.atmaFarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBs1DVAp4D-uxsJIf6BPvEHvhgCGPvizI',
    appId: '1:493354046889:ios:274e3a24706decff74a0b8',
    messagingSenderId: '493354046889',
    projectId: 'atma-palm-app-e2eb1',
    storageBucket: 'atma-palm-app-e2eb1.firebasestorage.app',
    iosBundleId: 'com.example.atmaFarmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiUU2azAcgwCZpnHKeRbyHGCAB5yeryoU',
    appId: '1:493354046889:web:53aad476809f5cf674a0b8',
    messagingSenderId: '493354046889',
    projectId: 'atma-palm-app-e2eb1',
    authDomain: 'atma-palm-app-e2eb1.firebaseapp.com',
    storageBucket: 'atma-palm-app-e2eb1.firebasestorage.app',
    measurementId: 'G-DBYD3VCD0W',
  );
}
