import 'package:flutter/material.dart';
// 1. Import the Firebase Core package
import 'package:firebase_core/firebase_core.dart';
// 2. Import the file generated by the FlutterFire CLI
import 'firebase_options.dart';
// 3. Import the WelcomeScreen you just created
import 'package:atma_farm_app/screens/welcome_screen.dart';

// 4. The main function MUST be async
void main() async {
  // 5. This is crucial to ensure all native code is ready before Firebase
  WidgetsFlutterBinding.ensureInitialized();
  // 6. This line initializes Firebase using the generated options file
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const AtmaPalmApp());
}

class AtmaPalmApp extends StatelessWidget {
  const AtmaPalmApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Atma-Palm',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.green,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.green.shade700,
            foregroundColor: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            padding: const EdgeInsets.symmetric(vertical: 16),
          ),
        ),
      ),
      // 7. Set the home property to the WelcomeScreen
      home: const WelcomeScreen(),
    );
  }
}

